config/routes.rb
Rails.application.routes.draw do
  resources :accessories
  devise_for :users
  # root to: "pages#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "accessories", to: "accessories#index"

  get "accessories/:id", to: "accessories#show"

  get 'accessories/:id/confirm', to: 'accessories#confirm', as: 'confirm_accessory'

  # Defines the root path route ("/")
  root to: "accessories#index"
  post "accessories", to: "accessories#create"
  get "accessories", to: "accessories#index"
  get "accessories/:id", to: "accessories#show"
  patch "accessories/:id", to: "accessories#update"
  delete "accessories/:id", to: "accessories#destroy"


end

app/models/accessory.rb
class Accessory < ApplicationRecord
  include PgSearch::Model
  multisearchable against: [:name, :description, :category, :condition, :location]
  #belongs_to :user

  CATEGORY = ['bags', 'shoes', 'belts', 'others', 'exotic', 'misc', 'footwear', 'clothes', 'jewllery']
  CONDITION = ['Brand New','Just out of the box', 'Mint', 'Loved a little', 'meh', 'worn out', 'on fire']

  validates :name, presence: true
  validates :description, presence: true
  validates :price_per_day, presence: true, numericality: { greater_than: 0 }
  validates :category, inclusion: { in: CATEGORY }

  alias_attribute :price, :price_per_day

  def reindex
    PgSearch::Multisearch.rebuild(self)
  end

  def self.search(query)
    where("name LIKE ? OR description LIKE ?", "%#{query}%", "%#{query}%")
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_many :accessories
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/accessories_controller.rb
class AccessoriesController < ApplicationController
  before_action :set_accessory, only: [:show, :edit, :update, :destroy, :confirm]
  # before_action :authorize_accessory, only: [:edit, :update, :destroy]

  def index
    if params[:query].present?
      @accessories = Accessory.where('name LIKE :query OR description LIKE :query OR category LIKE :query OR condition LIKE :query', query: "%#{params[:query]}%")
    else
      @accessories = Accessory.all
    end
  end

  def new
    @accessory = Accessory.new
  end

  def create
    @accessory = Accessory.new(accessory_params)
\

    if @accessory.save
      flash[:notice] = "Accessory was successfully created."
      redirect_to @accessory
    else
      flash[:alert] = "Accessory could not be created. " + @accessory.errors.full_messages.join(', ')
      render :new
    end
  end

  def show
  end

  def edit
    @object = Accessory.find(params[:id])
  end

  # app/controllers/accessories_controller.rb
  def update
    if @accessory.update(accessory_params)
      flash[:notice] = "Yay! 🎉 you successfully borrowed this item."
      redirect_to root_path
    else
      flash[:alert] = "Accessory could not be updated. " + @accessory.errors.full_messages.join(", ")
      render :edit
    end
  end

  def destroy
    @accessory.destroy
    flash[:notice] = "Accessory was successfully deleted."
    redirect_to accessories_path
  end

  private

  def accessory_params
    params.require(:accessory).permit(:name, :description, :price_per_day, :category, :condition, :location, :image)
  end

  def set_accessory
    @accessory = Accessory.find_by(id: params[:id])
    if @accessory.nil?
      flash[:alert] = "Accessory not found"
      redirect_to accessories_path
    end
  end

  def authorize_accessory
    unless @accessory.user == current_user
      flash[:alert] = "You are not authorized to perform this action."
      redirect_to @accessory
    end
  end
  def search
    if params[:query].present?
      @accessories = Accessory.search(params[:query])
      flash[:notice] = "Your search results" if @accessories.present?
      flash[:alert] = "No results were found" if @accessories.empty?
    else
      @accessories = Accessory.all
    end
    render 'search'
  end

  def confirm
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name)
  end

  def account_update_params
    params.require(:user).permit(:email, :password, :password_confirmation, :current_password, :first_name, :last_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def greeting_message
    if user_signed_in?
      "Hello, #{current_user.email}!"
    else
      "Welcome, guest!"
    end
  end
end

app/views/accessories/confirm.html.erb
<link rel="stylesheet" href="/assets/card_product_show-2da28b514cdeaa38c65d9ec049643dcecf7e23668b7d6ac19a79cc287e38ddb9.css" media="all" data-turbolinks-track="reload" />
<link rel="stylesheet" href="/assets/btn_ghost_show-6fc3f10effab37d29aa1190e88b5d80181376367f8e686c372ac3f6c9a7679f6.css" media="all" data-turbolinks-track="reload" />
<link rel="stylesheet" href="/assets/btn_flat_show-2eaf19f3d48a79a914f4a47070412a4a1636a160b74e28c131ea2fddfa1eace9.css" media="all" data-turbolinks-track="reload" />

<div class="container-fluid">
  <div class="row linha-2">
    <!-- Add your content here -->
  </div>

  <div class="container mt-5">
    <% flash.each do |type, message| %>
      <div class="flash flash-<%= type %> alert alert-dismissible fade show" role="alert">
        <span><%= message %></span>
        <a data-bs-dismiss="alert" aria-label="Close">
          <i class="fas fa-times"></i>
        </a>
      </div>
    <% end %>

    <div class="card-product-show">
      <div class="card-product-show-infos text-start">
        <h2>You are about to borrow: <%= @accessory.name %></h2>
        <%= link_to 'Borrow', accessory_path(@accessory), method: :put, class: 'btn btn-lg btn-flat-show borrow-button' %>
        <%= link_to 'Cancel', accessory_path(@accessory), class: 'btn btn-ghost-show' %>
      </div>
    </div>
  </div>
</div>

app/views/accessories/create.html.erb
<h1>Accessories#create</h1>
<p>Find me in app/views/accessories/create.html.erb</p>

app/views/accessories/destroy.html.erb
<h1>Accessories#destroy</h1>
<p>Find me in app/views/accessories/destroy.html.erb</p>

app/views/accessories/edit.html.erb
<%= simple_form_for @object do |f| %>
  <%= f.input :image, as: :file %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :price_per_day %>
  <%= f.input :location %>
  <%= f.input :category, collection: Accessory::CATEGORY %>
  <%= f.input :condition, collection: Accessory::CONDITION %>
  <%= f.submit "Update Accessory" %>
<% end %>

app/views/accessories/index.html.erb
<%# <h1 class="container">Fashion AirBnB</h1> %>

<% if @accessories.empty? %>
  <p>No accessories found for '<%= params[:query] %>'.</p>
  <p>Displaying all available accessories:</p>
  <% Accessory.all.each do |accessory| %>
    <div class="list-group-item">
  <div class="col-md-4 mb-4">
          <div class="card-item">
            <img src="<%= accessory.image %>" class="card-img-top" alt="<%= accessory.name %> Image">
            <div class="card-body">
              <h5 class="card-title"><%= accessory.name %></h5>
              <p class="card-text"><%=accessory.description%></p>
              <div class="button-group">
                <%= link_to "Details", accessory_path(accessory), class: "btn btn-success btn-sm mt-3" %>
                <%# if current_user == accessory.user %>
                <%= link_to 'Edit', edit_accessory_path(accessory), class: "btn btn-primary btn-sm mt-3" %>
                <%= link_to 'Remove', accessory_path(accessory),  data: {turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-warning btn-sm mt-3" %>
                <%# end %>
              </div>
            </div>
          </div>
        </div>
  <% end %>
<% else %>
  <% unless params[:query].nil? %>
    <p>Displaying results for '<%= params[:query] %>'.</p>
  <% end %>

  <div class="container">
    <ul class="list-group">
      <% @accessories.each do |accessory| %>
       <div class="col-md-4 mb-4">
          <div class="card-item">
            <img src="<%= accessory.image %>" class="card-img-top" alt="<%= accessory.name %> Image">
            <div class="card-body">
              <h5 class="card-title"><%= accessory.name %></h5>
              <p class="card-text"><%=accessory.description%></p>
              <div class="button-group">
                <%= link_to "Details", accessory_path(accessory), class: "btn btn-success btn-sm mt-3" %>
                <%# if current_user == accessory.user %>
                <%= link_to 'Edit', edit_accessory_path(accessory), class: "btn btn-primary btn-sm mt-3" %>
                <%= link_to 'Remove', accessory_path(accessory),  data: {turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-warning btn-sm mt-3" %>
                <%# end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </ul>

  <%= link_to 'New Accessory', new_accessory_path, class: 'btn btn-primary' %>
</div>

app/views/accessories/new.html.erb
<%= stylesheet_link_tag 'btn_flat_show', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="container">

  <div class="text-center mt-4 mb-4"><h1> List your accessory</h1>

  <%= simple_form_for @accessory, html: { class: 'my-form' } do |f| %>

    <div class="row">
      <div class="col-md-6 mt-4">
        <%= f.input :name, label: 'Name:', label_html: { class: 'control-label' }, input_html: { class: 'form-control' } %>
        <%= f.input :image, label: 'Image URL:', label_html: { class: 'control-label' }, input_html: { class: 'form-control' } %>
        <%= f.input :description, label: 'Description:', label_html: { class: 'control-label' }, input_html: { class: 'form-control' } %>
        <%= f.input :price_per_day, label: 'Price Per Day:', label_html: { class: 'control-label' }, input_html: { class: 'form-control' } %>
      </div>
      <div class="col-md-6 mt-4">
        <%= f.input :category, collection: Accessory::CATEGORY, label_html: { class: 'control-label' }, input_html: { class: 'form-control' } %>
        <%= f.input :condition, collection: Accessory::CONDITION, label_html: { class: 'control-label' }, input_html: { class: 'form-control' } %>
        <%= f.submit 'List Accessory', class: 'btn btn-flat-show btn-lg' %>
        <div>
        <%= link_to 'Back to Accessories', accessories_path, class: 'btn btn-flat-show mt-4' %>
        </div>
      </div>
    </div>
  <% end %>
<div>

app/views/accessories/search.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<% if flash[:alert] %>
  <p><%= flash[:alert] %></p>
<% end %>

<% @accessories.each do |accessory| %>
  <!-- Display each accessory -->
<% end %>

<%= link_to 'Back', accessories_path %>

app/views/accessories/show.html.erb
<%= stylesheet_link_tag 'card_product_show', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_link_tag 'btn_ghost_show', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_link_tag 'btn_flat_show', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class=" container mt-5">

  <div class="card-product-show">
    <%= image_tag("#{@accessory.image}")%>
    <div class="card-product-show-infos text-start">
      <h2><%= @accessory.name %></h2>
      <p><%= "Description: #{@accessory.description}" %></p>
      <p><%= "Category: #{@accessory.category}" %></p>
      <p><%= "Price per day: $#{@accessory.price_per_day}" %></p>
      <p><%# "Location: #{@accessory.location}" %></p>
      <p><%# @accessory.availability == true ? "Currently Available: Yes" : "Currently Available: No" %></p>
      <p><%= "Condition: #{@accessory.condition}" %></p>
      <p class="pt-2"><%= link_to "Borrow now", confirm_accessory_path(@accessory), class: "btn btn-lg btn-flat-show" %></p>
    </div>
  </div>

  <div class="text-center pt-5">
    <%= link_to "BACK", accessories_path, class: "btn btn-ghost-show" %>
  </div>
</div>

app/views/accessories/update.html.erb
<h1>Accessories#update</h1>
<p>Find me in app/views/accessories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbF</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render "shared/flashes" %>

  <div class="page-container">
    <div class="navbar-container"><%= render "shared/navbar" %></div>
    <div class="content-container"><%= yield %></div>
    <div class="footer-container"><%= render "shared/footer" %></div>
  </div>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer bg-dark text-light py-3 mt-3">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <p>&copy; 2023 Airbnb_F. All rights reserved.</p>
      </div>
      <div class="col-md-6 text-md-right">
        <p>Contact us: info@airbnb.fashion
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="container-fluid">
  <div class="row">
      <div class="navbar navbar-expand-sm navbar-light navbar-lewagon text-center">

      <div class="container-fluid">
        <%= link_to "#", class: "navbar-brand" do %>
          <%= image_tag "shop_my_closet.png" %>
        <% end %>
        <h1 class="navbar-brand mb-0 text-danger">Shop My Closet</h1>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
            <% if user_signed_in? %>
              <li class="nav-item active">
                <%= link_to "Home", "#", class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Messages", "#", class: "nav-link" %>
              </li>
              <li class="nav-item dropdown">
              <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
              </a>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <%= link_to "Action", "#", class: "dropdown-item" %>
                  <%= link_to "Another action", "#", class: "dropdown-item" %>
                  <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
                </div>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Login", new_user_session_path, class: "nav-link text-danger" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="row linha-2">
    <div class="links-wrapper text-uppercase">
      <div class="container">
        <div class="col-12 row p-0 justify-content-around align-items-center">
        <%# botar padding %>
          <div class="col"><p class="mb-0">Jewellery</p></div>
          <div class="col"><p class="mb-0">Clothing</p></div>
          <div class="col"><p class="mb-0">Footwear</p></div>
          <div class="col"><p class="mb-0">Bags</p></div>
          <div class="col"><p class="mb-0">Misc</p></div>
        </div>
      </div>
    </div>
  </div>
</div>